-- CREATE A NEW TABLE CALLED PERSONS WITH COLUMNS: ID, PERSON_NAME, BIRTH_DATE, AND PHONE

CREATE TABLE persons (
	id INT NOT NULL,
    person_name VARCHAR(50) NOT NULL,
	birth_date DATE,
    phone VARCHAR(15) NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

-- ADD NEW COLUMN CALLED EMAIL TO THE PERSONS TABLE

ALTER TABLE persons
ADD email VARCHAR(50) NOT NULL;

-- REMOVE COLUMN PHONE FROM PERSONS TABLE

ALTER TABLE persons
DROP COLUMN phone;

-- DELETE THE TABLE PERSONS FROM THE DATABASE

DROP TABLE persons;