-- Retrieve all customer data

SELECT *
FROM CUSTOMERS;

-- RETRIEVE ALL THE ORDER DATA

SELECT *
FROM orders;

-- RETRIEVE EACH CUSTOMER'S NAME, COUNTRY, AND SCORE

SELECT 
	first_name,
    country,
    score
FROM customers;

-- RETRIEVE CUSTOMERS SCORE NOT EQUAL TO 0

SELECT *
FROM customers
WHERE score != 0;

-- RETRIEVE CUSTOMER ARE FROM GERMANY

SELECT *
FROM customers
WHERE country = 'Germany';

-- RETRIEVE ALL CUSTOMERS AND SORT THE RESULTS BY THE HIGHEST SCORE FIRST;

SELECT *
FROM customers
ORDER BY score DESC; 

-- RETRIEVE THE CUSTOMERS AND SORT THE RESULTS BY THE LOWEST SCORE FIRST

SELECT *
FROM customers
ORDER BY score ASC;

-- RETRIEVE THE CUSTOMERS AND SORT THE RESULTS BY THE COUNTRY AND THEN BY THE HIGHEST SCORE.

SELECT *
FROM customers
ORDER BY country ASC, score DESC;

-- FIND THE TOTAL SCORES BY EACH COUNTRY
	-- TOTAL SCORE -> SUM() AGGREGATION FUNCTON
-- FOR EACH COUNTRY
	-- GROUP BY
-- COUNTRY-WISE TOTAL SCORES

SELECT country, SUM(score)
FROM customers
GROUP BY country; 

-- FIND THE TOTAL SCORE AND TOTAL NUMBER OF CUSTOMERS, FOR EACH COUNTRY
-- I. TOTAL SCORE -- > SUM(score)
-- II. TOTAL NUMBER OF CUSTOMERS (counting the rows) --> COUNT(*)
-- III. FOR EACH COUNTRY (COUNTRY WISE RESULT) -> Group by

SELECT 
	country,
    sum(score) AS total_scores,
    count(id) AS total_customers
FROM customers
GROUP BY country;

/* FIND THE AVERAGE SCORE FOR EACH COUNTRY, CONSIDERING ONLY CUSTOMERS WITH SCORE NOT EQUAL TO 0 
AND RETURN ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREATER THAN 430; */

-- I. FIND THE AVERAGE SCORE
	-- AVG(score)
    
-- II. FOR EACH COUNTRY
	-- GROUP BY country
    
-- III. CUSTOMER SCORE > 0
	-- WHERE score > 0
    
-- IV. COUNTRIES AVERAGE SCORE > 430
	-- HAVING AVG(score) > 430
    
SELECT 
	country,
    AVG(score)
FROM customers
WHERE score != 0
GROUP BY country
HAVING AVG(score) > 430;

-- RETURN UNIQUE LIST OF ALL COUNTRIES

SELECT DISTINCT country
FROM customers;

-- RETRIEVE ONLY 3 CUSTOMERS

SELECT *
FROM customers
LIMIT 3;

-- RETRIEVE THE TOP 3 CUSTOMERS WITH THE HIGHEST SCORES

-- I. HIGHEST SCORE
	-- SORT DATA IN DESCENDING ORDER
		-- ORDER BY SCORES DESC
-- II. TOP 3
	-- LIMIT 3
    
SELECT *
FROM customers
ORDER BY score DESC
LIMIT 3;

-- RETRIEVE THE LOWEST 2 CUSTOMERS BASED ON THE SCORE

SELECT *
FROM customers
ORDER BY score ASC
LIMIT 2;

-- GET THE TWO MOST RECENT ORDERS

SELECT * 
FROM orders
ORDER BY order_date DESC
LIMIT 2;