-- Conditional Operators

-- RETRIEVE ALL CUSTOMERS FROM GERMANY

SELECT *
FROM customers
WHERE country = 'Germany';

-- RETRIEVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY

SELECT *
FROM customers
WHERE country != 'Germany';

-- RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN 500

SELECT * 
FROM customers
WHERE score > 500;

-- RETRIEVE ALL CUSTOMERS WITH A SCORE GREATER THAN 500 AND MORE

SELECT *
FROM customers
WHERE score >= 500;

-- RETRIEVE ALL CUSTOMER WITH A SCORE LESS THAN 500

SELECT * 
FROM customers
WHERE score < 500;

-- RETRIEVE ALL CUSTOMERS WITH A SCORE LESS THAN 500 OR LESSER

SELECT *
FROM customers
WHERE score <= 500;

-- Logical Operators

-- RETRIEVE ALL CUSTOMERS WHO ARE FROM THE USA AND HAVE A SCORE GREATER THAN 500

SELECT *
FROM customers
WHERE country = 'USA' AND score > 500;

-- RETRIEVE ALL CUSTOMERS WHO ARE EITHER FROM USA OR HAVE A SCORE GREATER THAN 500

SELECT *
FROM customers
WHERE country = 'USA' OR score > 500;

-- RETRIEVE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500

SELECT * 
FROM customers
WHERE NOT score < 500;

-- RETRIEVE ALL CUSTOMERS WHOSE SCORE FALLS IN THE RANGE BETWEEN 100 & 500

SELECT *
FROM customers
WHERE score BETWEEN 100 AND 500;

-- RETRIEVE ALL CUSTOMERS FROM EITHER GERMANY OR USA

SELECT *
FROM customers 
WHERE country IN ('Germany', 'Usa');

SELECT *
FROM customers 
WHERE country  NOT IN ('Germany', 'Usa');

-- FIND ALL CUSTOMERS WHOSE FIRST NAME START WITH AN M

SELECT *
FROM customers
WHERE first_name LIKE 'M%';

-- FIND ALL CUSTOMERS WHOSE FIRST NAME ENDS WITH N

SELECT *
FROM customers
WHERE first_name LIKE '%n';

-- FIND ALL CUSTOMERS WHOSE FIRST NAME CONTAINS R

SELECT *
FROM customers
WHERE first_name LIKE '%r%';

-- RETRIEVE ALL CUSTOMERS WHOSE FIRST NAME HAS R IN THE 3RD POSITION

SELECT *
FROM customers
WHERE first_name LIKE '__r%';

